version: '3'
services:
  mysql:
    container_name: blog-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: tell
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    expose:
      - "3306"
    ports:
      - 3306:3306
    volumes:
      - ./tell-server/src/main/resources/db:/docker-entrypoint-initdb.d
      - ./mysql/mysql_data:/var/lib/mysql
    restart: always
