spring:
  datasource:
    #  数据源基本配置（请换成你自己的）
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/kxw?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver