server:
  port: 8080

spring:
  datasource:
    #  数据源基本配置
    #  username: sen
    #  password: 123
    #  url: jdbc:mysql://127.0.0.1:3306/kxw?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    #  driver-class-name: com.mysql.jdbc.Driver

    username: root
    password: Ms@972383371
    url: jdbc:mysql://120.79.94.184:3306/kxw?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  # configuration:
    # map-underscore-to-camel-case: true

# 打印SQL
logging:
  level:
    com.tell.mapper : debug
